POST http://localhost:3000/user/registro
Content-Type: application/json

{
    "userName": "",
    "email": "",
    "password": "",
    "sobreMi": "",
    "pregunta": "",
    "respuesta": "",
    "picture": ""
}

###

POST http://localhost:3000/
Content-Type: application/json

{
    "user": "",
    "password": ""
}