POST http://localhost:3000/user/registro
Content-Type: application/json

{
    "userName": "bruno88",
    "email": "brunocerutti88@gmail.com",
    "password": "123456",
    "sobreMi": "",
    "pregunta": "Resident Evil Favorito?",
    "respuesta": "Resident Evil 3",
    "picture": ""
}

###

POST http://localhost:3000/
Content-Type: application/json

{
    "user": "bruno88",
    "password": "123456"
}

